#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  🤖 AI EMPLOYEE — Prospects Dashboard
#
#  Regenerates PROSPECTS-DASHBOARD.md from PROSPECTS.md + daily/approvals.md.
#  Run anytime to refresh the view.
#
#  Usage:  bash scripts/dashboard.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
cd "$(dirname "$0")/.."   # → ai-employee/

OUT="PROSPECTS-DASHBOARD.md"
PROSPECTS="PROSPECTS.md"
APPROVALS="daily/approvals.md"
TODAY="$(date '+%Y-%m-%d')"
NOW="$(date '+%Y-%m-%d %H:%M EAT')"

# Count active prospects (## headers in PROSPECTS.md that look like prospect names)
TOTAL=$(grep -c "^### " "$PROSPECTS" 2>/dev/null || echo 0)

# Count drafts awaiting approval (lines starting with "  - [ ] Send" in approvals.md)
AWAITING=$(grep -c "^- \[ \] \*\*Send" "$APPROVALS" 2>/dev/null || echo 0)

# Pull prospect list (### lines)
PROSPECT_LINES=$(grep "^### " "$PROSPECTS" 2>/dev/null | head -20)

# Build dashboard
cat > "$OUT" <<HEADER
# 🎯 PROSPECTS DASHBOARD — Pipeline at a Glance

*Auto-updated by \`bash scripts/dashboard.sh\` — last run: $NOW*

---

## 📊 Pipeline Summary

| Metric | Count |
|--------|------:|
| Prospects tracked | **$TOTAL** |
| Drafts awaiting approval | **$AWAITING** |
| Sent this week | 0 |
| Replies received | 0 |
| Meetings booked | 0 |

---

## 👤 Prospects (from PROSPECTS.md)

| Prospect | Stage | Notes |
|----------|-------|-------|
HEADER

# Append prospect names
echo "$PROSPECT_LINES" | sed 's/^### /| /' | sed 's/$/ |  |  |/' >> "$OUT"

cat >> "$OUT" <<MIDDLE

---

## ⏸️ Drafts Awaiting Approval (from daily/approvals.md)
MIDDLE

# Pull approval items
grep "^- \[ \] \*\*Send" "$APPROVALS" 2>/dev/null | sed 's/^- \[ \] /- /' >> "$OUT" || echo "- (none)" >> "$OUT"

cat >> "$OUT" <<FOOTER

---

## 📋 How to Use This Dashboard

1. **Refresh anytime:** \`bash scripts/dashboard.sh\`
2. **Add a prospect:** edit PROSPECTS.md (add a block starting with \`### [Name]\`)
3. **Add a draft:** write in daily/inbox.md, add a checkbox line in daily/approvals.md
4. **Approve a draft:** tick the box in approvals.md, send, the next run will reflect it
5. **Review before send:** check [APPROVALS-CHECKLIST.md](APPROVALS-CHECKLIST.md) — 7-point gate

---

*Generated by \`scripts/dashboard.sh\` — run anytime to refresh.*
FOOTER

echo "✅ Dashboard refreshed: $OUT"
echo "   Prospects: $TOTAL · Drafts awaiting: $AWAITING"
